name: GitHub Release
on:
  push:
    branches: [ ci ]
    tags:
      - 'v*.*'
jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2022
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Get the project's version
        uses: kzrnm/get-net-sdk-project-versions-action@v2.0.0
        id: get-version
        with:
          proj-path: KHFM-VF-Patch/KHFM-VF-Patch.csproj

      - name: Build Binary
        shell: cmd
        run: call .\CI\Build.cmd

      - name: Create Artifact
        shell: cmd
        run: call .\CI\CreateArtifact.cmd

      - name: Rename Artifact with project version
        shell: cmd
        run: mv ./KHFM-VF-Patch/KHFM-VF-Patch.zip ./KHFM-VF-Patch/KHFM-VF-Patch-${{ steps.get-version.outputs.version }}.zip

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ./KHFM-VF-Patch/KHFM-VF-Patch-${{ steps.get-version.outputs.version }}.zip
          draft: true
          prerelease: true
